name: pico_control
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.2
  auto_route: ^7.8.4
  flutter_riverpod: ^2.4.9
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
